# Generated by Django 3.2.7 on 2021-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=300)),
                ('short_url', models.CharField(blank=True, max_length=15, unique=True)),
            ],
        ),
    ]
